### ISSUE TITLE
Is it spec-compliant to const-fold and -propagate non-deterministic instructions?

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/relaxed-simd#155]
Forgive me if I just missed the relevant bits[^missed], but reading through the spec, it isn't 100% clear to me whether constant folding and propagation through non-deterministic instructions is spec-compliant.

The "risk" here is that Wasm could observe whether these optimizations happened or not if

* the wasm is compiled on a machine that has native support for `fma` (for example)
* the wasm is evaluated on a machine that does not

Or alternatively, maybe the compiler's compile-time evaluation of the `fma` is in software, but runtime-evaluated `fma`s use the hardware, and these two implementations have different behavior (that are each individually spec-compliant).

Basically: is it spec-compliant if two instances of the same instruction make different choices of how to evaluate a non-deterministic instruction?

I see https://github.com/WebAssembly/relaxed-simd/blob/main/document/core/exec/numerics.rst#relaxed-operations which seems to suggest the answer is "no, the above optimizations are not spec-compliant" because it says that operations are "fixed to one particular choice by the execution environment". However, looking at [the semantics of `fma` in particular](https://github.com/WebAssembly/relaxed-simd/blob/main/document/core/exec/numerics.rst#fmaz_1-z_2-z_3) there is no spec machinery there that fixes these choices across the whole execution environment, as far as I can tell.

Thanks in advance for the clarification!

[^missed]: It was kind of hard to look through the spec for this stuff, because for whatever reason, the built and rendered version of the modified spec isn't available anymore (if it ever was?) and so I was browsing through the spec sources on github's UI. Might be something one of the champions is interested in fixing, at least until this proposal is merged into the main spec and we can view the relevant, rendered bits there.

**Comment by rossberg** [comment]
That is not allowed, unless constant folding is guaranteed to implement the same semantics as execution on the host machine. This is a consequence of the new form of non-determinism introduced by this proposal which essentially codifies implementation-dependent behaviour, and guarantees that to be consistent across all executions of the same class of instruction.

That specifically means that offline tools like Binaryen cannot correctly (i.e., in a semantics-preserving manner) perform such optimisations, since they do not know the target architecture's behaviour.

I don't remember if that issue was discussed specifically, but it is a (simpler) instance of the general phasing problem that _was_ discussed, the more hypothetical scenario of code mobility: if a Wasm program is partially executed on one machine, and then hibernated and later resumed on another machine/engine, then that would only be legal if the implementations made sure they both implement the exact same behaviour. In practice, that might be impossible to achieve.

My impression is that we still do not properly understand the implications of this fundamental change to Wasm and its effect on portability and the meaning of program execution. It is too loose to constrain implementations sufficiently, but too strict to prevent user code from making problematic global assumptions.

**Comment by fitzgen** [comment]
@rossberg thanks!

> That is not allowed, unless constant folding is guaranteed to implement the same semantics as execution on the host machine. This is a consequence of the new form of non-determinism introduced by this proposal which essentially codifies implementation-dependent behaviour, and guarantees that to be consistent across all executions of the same class of instruction.

Can you share where in the spec this consistency guarantee for the new form of non-determinism is codified?

**Comment by fitzgen** [comment]
Gotcha. So it is intended, but not formally spec'd yet.

In that case, I can look into adding some spec test like

```wat
(func (export "test") (param v128 v128)
  local.get 0
  local.get 1
  relaxed_whatever
  v128.const ...
  v128.const ...
  relaxed_whatever
  v128.eq
)

;; Pass in the same values as dynamic arguments that are static constants
;; inside the function and assert the non-deterministic results are the
;; same.
(assert_return (invoke "test" (v128.const ...) (v128.const ...)) (i32.const 1))
```

**Comment by rossberg** [comment]
Sounds good!

**Comment by fitzgen** [comment]
Added a test in https://github.com/WebAssembly/relaxed-simd/pull/156, would appreciate a review and merge!
