### ISSUE TITLE
SIMD subgroup meeting on 2022-10-14

### ISSUE THREAD

**Issue by penzn** [WebAssembly/relaxed-simd#91]
I suggest we have another meeting before the Phase 4 vote for relaxed-simd. In a similar situation with SIMD proposal we used to meet bi-weekly.

If there is interest, then meeting will be on Friday, October 14th at 9:00AM - 10:00AM PDT/ 5:00PM - 6:00PM CET.

I will send out an invite using the same list of attendees as in regular meeting. Anyone new or needing an invite, please comment on the issue.

**Comment by penzn** [comment]
I've sent the invite, and it looks like at all conference rooms declined, so if anyone is going to use a Google conference room it can be an issue.

**Comment by ngzhian** [comment]
I'm slowly moving towards the "add FMA and leave set determinism alone" path. This goes a bit counter to our original goal of "relax determinism to make things go fast", but I'm sensing strong push backs that, and since there is a way forward, I would like to see if we can make it work.
Adding fixed FMA is a bit of a scope creep and out of relaxed-simd, but it does help us get what we want, a fast FMA when available.
There are suggestions to also add scalar FMA and scalar QFMA while we are at it, perhaps we should discuss if this make sense.

**Comment by ngzhian** [comment]
Notes are at https://github.com/WebAssembly/meetings/blob/main/simd/2022/SIMD-10-14.md
